SELECT TOP (1000) [id]
      ,[userID]
      ,[PublishedName]
      ,[Date]
      ,[Title]
      ,[Image]
      ,[Description]
      ,[Category]
      ,[Tags]
      ,[isPublished]
      ,[isDeleted]
  FROM [dbo].[BlogInfo]